version: '3.8'

services:
  bot:
    build: .
    container_name: lithtgbot
    restart: unless-stopped
    command: python3 main.py
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - celery_worker

  celery_worker:
    build: .
    container_name: lithtgbot_worker
    restart: unless-stopped
    command: celery -A tasks.celery worker -l info
    env_file:
      - .env
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: lithtgbot_beat
    restart: unless-stopped
    command: celery -A tasks.celery beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - celery_worker
